### ISSUE TITLE
[CHORE]: Refactor app.js and others to simplify adding functionality into htmx and slide over style html pages.

### ISSUE THREAD

**Issue by imAsparky** [imAsparky/django-ckeditors#51]
**What is the chore?**

**Comment by imAsparky** [comment]
@robinchew perhaps this may solve our problem, rather than listening for `DOMContentLoaded` to set up the CKE toolbars etc  we listen for the `class` or `id`  being settled and run the setup then.

**Comment by robinchew** [comment]
> @robinchew perhaps this may solve our problem, rather than listening for `DOMContentLoaded` to set up the CKE toolbars etc we listen for the `class` or `id` being settled and run the setup then.

yes, if by settled you mean immediately after the <textarea> there is a <script> tag that instantiates CKE toolbar for that textarea.

**Comment by imAsparky** [comment]
completed in various other issues.
